name: WR PR Trigger
on:
  workflow_run:
    workflows: ["PR Trigger"]
    types: [completed]

jobs:
  Last-Workflow-Success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/github-script@v4
        with:
          script: |
            const script = require('./.github/js/wr-pr-trigger/add-linked-issue-labels-to-pr/download-artifact.js')
            const artifact = script({ g: github, c: context })
            return artifact
      - run: unzip add-linked-issue-labels-to-pr.zip

      - name: Read data from add-linked-issue-labels-to-pr artifact
        uses: actions/github-script@v4
        # Variable that stores result of script
        id: artifact
        with:
          script: |
            // Retrieve pull request and issue number from downloaded artifact
            const fs = require('fs')
            if(fs.existsSync('artifact.txt')){
              const artifact = fs.readFileSync('artifact.txt')
              console.log('artifact: ', JSON.parse(artifact))
            }
          
  Last-Workflow-Failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Failed Run
        run: echo "The previous GitHub Action failed. Please check the logs for the previous action."